### ISSUE TITLE
O kaip su pleciamumu? Jei reiktu prideti X taisykliu ir Y salygu, si kodo vieta sprogtu :)

### ISSUE THREAD

**Issue by kestutisbartkus** [marijus-saulys/skycop-task#1]
https://github.com/marijus-saulys/skycop-task/blob/ae265de02cfa78dab5356f6e3f898881bcc7f9ec/src/Model/DecisionTable/Table/Claimable.php#L53

**Comment by kestutisbartkus** [comment]
Tarkim, atsirando realus poreikis: reikia pradeti vertinti laika, spec saliu sarasa ir kad 3 pozymius.

**Comment by marijus-saulys** [comment]
Gal nepilnai supratau, bet ar sekantis commit'as neišsprendžia šitos problemos? Dabar galima prisikurt kiek nori, kokių nori taisyklių ir prisiinjectint bet kokią jų kombinaciją į norimą decision table'ą. Gal tik tada perdaryčiau DepartureFromEU į DepartureFrom ir atitinkamai suinjectinčiau norimą šalių sąrašą atitinkamai lentelei.

**Comment by kestutisbartkus** [comment]
Ok. Dekui uz sprendima.
